version: "3.5"

services:

  nginx:
    volumes:
      - ./../../${M2C_CFG_MAGENTO_SRC}/:/var/www/html

  php:
    volumes:
      - ~/.composer:/var/www/.composer
      - ~/.m2c/ssl/certs:/usr/share/ca-certificates/m2c:ro
      - ./../../${M2C_CFG_MAGENTO_SRC}/:/var/www/html