version: "3.5"

services:

  nginx:
    container_name: ${M2C_CFG_DOMAIN_NAME}__nginx
    hostname: ${M2C_CFG_DOMAIN_NAME}__nginx
    image: mage2click/m2c:nginx-${M2C_CFG_NGINX:-1.17}-alpine
    depends_on:
      - db
      - php

  varnish:
    container_name: ${M2C_CFG_DOMAIN_NAME}__varnish
    hostname: ${M2C_CFG_DOMAIN_NAME}__varnish
    image: mage2click/m2c:varnish-${M2C_CFG_VARNISH:-5.2}-alpine
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.varnish-${M2C_PROJECT_NAME}.tls=true
      - traefik.http.routers.varnish-${M2C_PROJECT_NAME}.entryPoints=https
      - traefik.http.routers.varnish-${M2C_PROJECT_NAME}.rule=Host(`${M2C_CFG_DOMAIN_NAME}`)
      - traefik.http.services.varnish-${M2C_PROJECT_NAME}.loadbalancer.server.port=80
    networks:
      - m2c
      - default