version: "3.5"

services:

  nginx:
    environment:
      - UID=${M2C_CFG_UID}
      - GID=${M2C_CFG_GID}
    volumes:
      - ./../../${M2C_CFG_MAGENTO_SRC}/:/var/www/html:ro
      - sock_data:/sock

  php:
    environment:
      - UID=${M2C_CFG_UID}
      - GID=${M2C_CFG_GID}
    volumes:
      - ~/.composer:/var/www/.composer
      - ~/.m2c/ssl/certs:/usr/share/ca-certificates/m2c:ro
      - ./../../${M2C_CFG_MAGENTO_SRC}/:/var/www/html
      - sock_data:/sock

  xdebug:
    environment:
      - UID=${M2C_CFG_UID}
      - GID=${M2C_CFG_GID}
    volumes:
      - ~/.composer:/var/www/.composer
      - ~/.m2c/ssl/certs:/usr/share/ca-certificates/m2c:ro
      - ./../../${M2C_CFG_MAGENTO_SRC}/:/var/www/html
      - sock_data:/sock

volumes:
  sock_data: