version: "3.5"

services:

  rabbitmq:
    container_name: ${M2C_CFG_DOMAIN_NAME}__rabbitmq
    image: rabbitmq:${M2C_CFG_RABBITMQ:-3.7}-management-alpine
    labels:
      - traefik.enable=true
      - traefik.port=15672
      - traefik.frontend.rule=Host:rabbitmq.${M2C_CFG_DOMAIN_NAME}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      default:
        aliases:
          - rabbitmq.${M2C_CFG_DOMAIN_NAME}
      m2c:
        aliases:
          - rabbitmq.${M2C_CFG_DOMAIN_NAME}

volumes:
  rabbitmq_data: