version: "3.5"

services:

  phpmyadmin:
    container_name: ${M2C_CFG_DOMAIN_NAME}__phpmyadmin
    hostname: ${M2C_CFG_DOMAIN_NAME}__phpmyadmin
    image: phpmyadmin/phpmyadmin:fpm-alpine
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:pma.${M2C_CFG_DOMAIN_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${M2C_CFG_MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_USER=${M2C_CFG_MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${M2C_CFG_MYSQL_PASSWORD:-magento}
      - PMA_ABSOLUTE_URI=https://pma.${M2C_CFG_DOMAIN_NAME}/
      - PMA_HOST=${M2C_CFG_DOMAIN_NAME}__db
    networks:
      - m2c
      - default