[api]
  dashboard = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.mysql]
    address = ":3306"

[providers]
  [providers.docker]
    exposedByDefault = false
    network = "m2c"
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
