version: "3.5"

services:

  mailhog:
    container_name: m2c.test__mailhog
    hostname: mailhog
    image: mailhog/mailhog:${M2C_GLOBAL_MAILHOG}
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mailhog.m2c.test
      - traefik.port=8025
    restart: ${M2C_GLOBAL_SERVICES_AUTO_START}