version: "3.5"

services:

  mage2click:
    container_name: m2c.test__mage2click
    image: mage2click/m2c:home
    ports:
      - "127.0.0.1:33060:22/tcp"
    labels:
      - traefik.passHostHeader=true
      - traefik.enable=true
      - traefik.frontend.rule=Host:m2c.test
      - traefik.port=8080
    restart: ${M2C_GLOBAL_SERVICES_AUTO_START}

  traefik:
    container_name: m2c.test__traefik
    image: traefik:1.7-alpine
    command:
      - --api
      - --docker
      - --docker.domain=test
      - --docker.network=m2c
      - --docker.exposedByDefault=false
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ~/.m2c/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ~/.m2c/ssl/certs/m2c.crt:/etc/ssl/certs/m2c.crt:ro
      - ~/.m2c/ssl/private/m2c.key:/etc/ssl/private/m2c.key:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.m2c.test
      - traefik.port=8080
    restart: ${M2C_GLOBAL_SERVICES_AUTO_START}

  dnsmasq:
    container_name: m2c.test__dnsmasq
    image: mage2click/m2c:dnsmasq
    ports:
      - "127.0.0.1:53:53/udp"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dnsmasq.m2c.test
      - traefik.port=8080
    restart: ${M2C_GLOBAL_SERVICES_AUTO_START}

networks:
  default:
    name: m2c